### ISSUE TITLE
web wasm support

### ISSUE THREAD

**Issue by aakhalilian** [blackhorse-one/stomp_dart_client#110]
building web --wasm is successful but after running stomp client connect will throw this error in the console:
```
'No implementation of the connect api provided'
```
I think it's because in web assembly dart.library.html is not there nor is dart.library.io

```
import 'connect_api.dart'
    if (dart.library.html) 'connect_html.dart'
    if (dart.library.io) 'connect_io.dart' as platform;
```
https://github.com/blackhorse-one/stomp_dart_client/blob/master/lib/src/stomp_handler.dart#L14

is there a plan to fix it and support web assembly?

**Comment by KammererTob** [comment]
Hey,

thanks for the ticket. I'll have to look into that. I am not sure if the package `WebSocketChannel` that we are currently using supports this, but we might move to https://pub.dev/packages/web_socket in the future anyways.

So to answer the question: Yes, we plan to also support web assembly, but i have to look into it.

**Comment by aakhalilian** [comment]
@KammererTob yes I can pull from github in my pubspec and trying it. Will update in a few hours.

Thanks for quick turnaround

**Comment by aakhalilian** [comment]
@KammererTob the update has resolved our issue, pulling the branch:
```
#  stomp_dart_client: ^2.1.0
  stomp_dart_client:
    git:
      url: https://github.com/blackhorse-one/stomp_dart_client.git
      ref: wasm-support
```
